# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase"
    commit-message:
      prefix: "chore"
      include: "scope"

    groups:
      eslint:
        patterns:
          - "eslint"
          - "@eslint/js"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - "typescript-eslint"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/coverage-v8"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
